/**
 * Default dashboard.
 *
 * Ported from the Grafana dashboard in devops-land/mongodb_ftdc_viewer (MIT), which is
 * itself a descendant of zelmario/Big-hole. Generated by tools/port/port-dashboard.py --
 * regenerate rather than hand-editing if the upstream dashboard changes.
 *
 * Grafana applied derivative() to most panels, so those metrics are wrapped in rate()
 * here. Panels whose Flux fanned out over a regex (per-disk, per-replica-member) use a `*`
 * glob, expanded against the capture catalogue at load time.
 *
 * Grid is 24 columns to match Grafana 1:1.
 */

import type { Unit } from '../data/expr.js';

export interface PanelTemplate {
  readonly kind: 'chart' | 'section';
  readonly title: string;
  readonly metrics: readonly string[];
  readonly unit?: Unit;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export const DEFAULT_TEMPLATES: readonly PanelTemplate[] = [
  { kind: "section", title: "WiredTiger", metrics: [], x: 0, y: 0, w: 24, h: 1 },
  { kind: "chart", title: "WiredTiger Tickets", metrics: ["serverStatus.wiredTiger.concurrentTransactions.write.available", "serverStatus.wiredTiger.concurrentTransactions.read.available"], unit: "count", x: 0, y: 1, w: 14, h: 6 },
  { kind: "chart", title: "WiredTiger cache", metrics: ["serverStatus.wiredTiger.cache.maximum bytes configured", "serverStatus.wiredTiger.cache.bytes currently in the cache"], unit: "bytes", x: 14, y: 1, w: 10, h: 6 },
  { kind: "chart", title: "Mb read into cache / written from cache", metrics: ["rate(serverStatus.wiredTiger.cache.bytes written from cache)", "rate(serverStatus.wiredTiger.cache.bytes read into cache)"], unit: "bytes/s", x: 0, y: 7, w: 6, h: 6 },
  { kind: "chart", title: "Pages Evicted", metrics: ["rate(serverStatus.wiredTiger.cache.modified pages evicted)", "rate(serverStatus.wiredTiger.cache.unmodified pages evicted)"], unit: "per-sec", x: 6, y: 7, w: 8, h: 6 },
  { kind: "chart", title: "Dirty mb in the cache", metrics: ["serverStatus.wiredTiger.cache.tracked dirty bytes in the cache"], unit: "bytes", x: 14, y: 7, w: 10, h: 7 },
  { kind: "chart", title: "Mb written for checkpoint", metrics: ["rate(serverStatus.wiredTiger.block-manager.bytes written for checkpoint)"], unit: "bytes/s", x: 0, y: 13, w: 6, h: 6 },
  { kind: "chart", title: "wiredTiger Block Manager", metrics: ["rate(serverStatus.wiredTiger.block-manager.bytes read)", "rate(serverStatus.wiredTiger.block-manager.bytes written)"], unit: "bytes/s", x: 6, y: 13, w: 8, h: 6 },
  { kind: "chart", title: "WiredTiger Data Handle", metrics: ["serverStatus.wiredTiger.data-handle.connection data handles currently active"], unit: "count", x: 14, y: 14, w: 10, h: 5 },
  { kind: "section", title: "Server Status", metrics: [], x: 0, y: 19, w: 24, h: 1 },
  { kind: "chart", title: "Memory", metrics: ["serverStatus.mem.virtual", "serverStatus.mem.resident"], unit: "bytes", x: 0, y: 20, w: 8, h: 5 },
  { kind: "chart", title: "Page faults", metrics: ["rate(serverStatus.extra_info.page_faults)"], unit: "per-sec", x: 8, y: 20, w: 7, h: 5 },
  { kind: "chart", title: "Connections", metrics: ["rate(serverStatus.connections.active)", "rate(serverStatus.connections.current)", "rate(serverStatus.connections.totalCreated)"], unit: "per-sec", x: 15, y: 20, w: 9, h: 7 },
  { kind: "chart", title: "Latency", metrics: ["rate(serverStatus.opLatencies.reads.latency)", "rate(serverStatus.opLatencies.writes.latency)", "rate(serverStatus.opLatencies.commands.latency)"], unit: "us", x: 0, y: 25, w: 8, h: 7 },
  { kind: "chart", title: "Operations", metrics: ["rate(serverStatus.opcounters.update)", "rate(serverStatus.opcounters.query)", "rate(serverStatus.opcounters.insert)", "rate(serverStatus.opcounters.getmore)", "rate(serverStatus.opcounters.delete)", "rate(serverStatus.opcounters.command)"], unit: "per-sec", x: 8, y: 25, w: 7, h: 7 },
  { kind: "chart", title: "Network requests", metrics: ["rate(serverStatus.network.numRequests)"], unit: "per-sec", x: 15, y: 27, w: 9, h: 5 },
  { kind: "chart", title: "Current Queue writers / readers", metrics: ["serverStatus.globalLock.currentQueue.writers", "serverStatus.globalLock.currentQueue.readers"], unit: "count", x: 0, y: 32, w: 8, h: 6 },
  { kind: "chart", title: "Replica members health", metrics: ["replSetGetStatus.members.0.health", "replSetGetStatus.members.1.health", "replSetGetStatus.members.2.health"], unit: "count", x: 8, y: 32, w: 7, h: 6 },
  { kind: "chart", title: "Replica members lag", metrics: ["diff(serverStatus.localTime, replSetGetStatus.members.*.lastAppliedWallTime)"], unit: "ms", x: 15, y: 32, w: 9, h: 6 },
  { kind: "chart", title: "Operations latencies op", metrics: ["rate(serverStatus.opLatencies.reads.ops)", "rate(serverStatus.opLatencies.writes.ops)", "rate(serverStatus.opLatencies.commands.ops)"], unit: "us", x: 0, y: 38, w: 8, h: 5 },
  { kind: "chart", title: "Server Uptime", metrics: ["serverStatus.uptime"], unit: "count", x: 8, y: 38, w: 7, h: 5 },
  { kind: "chart", title: "Replica members ping", metrics: ["replSetGetStatus.members.*.pingMs"], unit: "ms", x: 15, y: 38, w: 9, h: 5 },
  { kind: "chart", title: "FlowControl isLagged", metrics: ["rate(serverStatus.flowControl.isLaggedTimeMicros)"], unit: "us", x: 0, y: 43, w: 8, h: 6 },
  { kind: "chart", title: "Asserts", metrics: ["rate(serverStatus.asserts.warning)", "rate(serverStatus.asserts.user)", "rate(serverStatus.asserts.rollovers)", "rate(serverStatus.asserts.regular)", "rate(serverStatus.asserts.msg)"], unit: "per-sec", x: 8, y: 43, w: 7, h: 7 },
  { kind: "chart", title: "Query Executor", metrics: ["rate(serverStatus.metrics.queryExecutor.scannedObjects)", "rate(serverStatus.metrics.queryExecutor.scanned)", "rate(serverStatus.metrics.queryExecutor.collectionScans.total)"], unit: "per-sec", x: 15, y: 43, w: 9, h: 6 },
  { kind: "chart", title: "Commands", metrics: ["rate(serverStatus.metrics.commands.createIndexes.total)", "rate(serverStatus.metrics.commands.dataSize.total)", "rate(serverStatus.metrics.commands.dropIndexes.total)", "rate(serverStatus.metrics.commands.listCollections.total)", "rate(serverStatus.metrics.commands.listDatabases.total)"], unit: "per-sec", x: 0, y: 49, w: 8, h: 6 },
  { kind: "chart", title: "avg Obj Size", metrics: ["local.oplog.rs.stats.storageStats.avgObjSize"], unit: "count", x: 15, y: 49, w: 9, h: 6 },
  { kind: "chart", title: "Cursors", metrics: ["serverStatus.metrics.cursor.open.noTimeout", "serverStatus.metrics.cursor.open.pinned", "serverStatus.metrics.cursor.open.total", "serverStatus.metrics.cursor.timedOut"], unit: "count", x: 8, y: 50, w: 7, h: 6 },
  { kind: "chart", title: "Documents (deleted / inserted / returned / updated)", metrics: ["rate(serverStatus.metrics.document.updated)", "rate(serverStatus.metrics.document.returned)", "rate(serverStatus.metrics.document.inserted)", "rate(serverStatus.metrics.document.deleted)"], unit: "per-sec", x: 0, y: 55, w: 8, h: 7 },
  { kind: "chart", title: "Opcounters Replica", metrics: ["rate(serverStatus.opcountersRepl.command)", "rate(serverStatus.opcountersRepl.delete)", "rate(serverStatus.opcountersRepl.getmore)", "rate(serverStatus.opcountersRepl.insert)", "rate(serverStatus.opcountersRepl.query)", "rate(serverStatus.opcountersRepl.update)"], unit: "per-sec", x: 15, y: 55, w: 9, h: 7 },
  { kind: "chart", title: "Query Targeting: Scanned Objects / Returned ", metrics: ["serverStatus.metrics.document.returned", "serverStatus.metrics.queryExecutor.scannedObjects"], unit: "count", x: 8, y: 56, w: 7, h: 6 },
  { kind: "section", title: "System", metrics: [], x: 0, y: 62, w: 24, h: 1 },
  { kind: "chart", title: "Network In / Out physical", metrics: ["rate(serverStatus.network.physicalBytesIn)", "rate(serverStatus.network.physicalBytesOut)"], unit: "bytes/s", x: 0, y: 63, w: 8, h: 5 },
  { kind: "chart", title: "Network In / Out", metrics: ["rate(serverStatus.network.bytesOut)", "rate(serverStatus.network.bytesIn)"], unit: "per-sec", x: 8, y: 63, w: 8, h: 6 },
  { kind: "chart", title: "Storage Size", metrics: ["local.oplog.rs.stats.storageStats.freeStorageSize", "local.oplog.rs.stats.storageStats.storageSize"], unit: "bytes", x: 16, y: 63, w: 8, h: 6 },
  { kind: "chart", title: "CPU Usage", metrics: ["scale(rate(systemMetrics.cpu.user_ms), 0.1)", "scale(rate(systemMetrics.cpu.system_ms), 0.1)", "scale(rate(systemMetrics.cpu.iowait_ms), 0.1)", "scale(rate(systemMetrics.cpu.nice_ms), 0.1)", "scale(rate(systemMetrics.cpu.softirq_ms), 0.1)", "scale(rate(systemMetrics.cpu.steal_ms), 0.1)", "scale(rate(systemMetrics.cpu.idle_ms), 0.1)"], unit: "percent", x: 0, y: 68, w: 8, h: 6 },
  { kind: "chart", title: "Disk writes and reads", metrics: ["rate(systemMetrics.disks.*.reads)", "rate(systemMetrics.disks.*.writes)"], unit: "per-sec", x: 8, y: 69, w: 8, h: 7 },
  { kind: "chart", title: "Memory", metrics: ["scale(systemMetrics.memory.MemAvailable_kb, 1024)", "scale(systemMetrics.memory.MemFree_kb, 1024)"], unit: "bytes", x: 16, y: 69, w: 8, h: 7 },
  { kind: "chart", title: "Disk I/O", metrics: ["rate(systemMetrics.disks.*.io_time_ms)", "systemMetrics.disks.*.io_in_progress"], unit: "count", x: 0, y: 74, w: 8, h: 7 },
  { kind: "chart", title: "Disk writes", metrics: ["rate(systemMetrics.disks.*.write_sectors)", "rate(systemMetrics.disks.*.write_time_ms)"], unit: "count", x: 8, y: 76, w: 8, h: 7 },
  { kind: "chart", title: "Swap Memory", metrics: ["scale(systemMetrics.memory.SwapFree_kb, 1024)", "scale(systemMetrics.memory.SwapTotal_kb, 1024)"], unit: "count", x: 16, y: 76, w: 8, h: 7 },
  { kind: "chart", title: "Disk reads", metrics: ["rate(systemMetrics.disks.*.read_sectors)", "rate(systemMetrics.disks.*.read_time_ms)"], unit: "count", x: 0, y: 81, w: 8, h: 7 },
  { kind: "chart", title: "TCP ActiveOpens / AttemptFails / EstabResets", metrics: ["rate(systemMetrics.netstat.Tcp:ActiveOpens)", "rate(systemMetrics.netstat.Tcp:AttemptFails)", "rate(systemMetrics.netstat.Tcp:EstabResets)"], unit: "per-sec", x: 8, y: 83, w: 8, h: 7 },
  { kind: "chart", title: "TCP: InSegs / OutSegs", metrics: ["rate(systemMetrics.netstat.Tcp:InSegs)", "rate(systemMetrics.netstat.Tcp:OutSegs)"], unit: "per-sec", x: 16, y: 83, w: 8, h: 5 },
  { kind: "chart", title: "TCP Routing Issues", metrics: ["rate(systemMetrics.netstat.Ip:OutNoRoutes)"], unit: "per-sec", x: 0, y: 88, w: 8, h: 5 },
  { kind: "chart", title: "TCP Connection Issues", metrics: ["rate(systemMetrics.netstat.Tcp:CurrEstab)", "rate(systemMetrics.netstat.Tcp:EstabResets)", "rate(systemMetrics.netstat.Tcp:OutRsts)"], unit: "per-sec", x: 8, y: 90, w: 8, h: 7 },
  { kind: "chart", title: "TCP Packet Loss or Corruption", metrics: ["rate(systemMetrics.netstat.Tcp:InCsumErrors)", "rate(systemMetrics.netstat.Tcp:InErrs)", "rate(systemMetrics.netstat.Tcp:RetransSegs)", "rate(systemMetrics.netstat.Ip:InDiscards)", "rate(systemMetrics.netstat.Ip:OutDiscards)"], unit: "per-sec", x: 0, y: 93, w: 8, h: 5 },
];

