/**
 * Default dashboard.
 *
 * Ported panel for panel from zelmario/Big-hole (grafana/dashboards/dashboard.json,
 * vendored at tools/port/big-hole-dashboard.json). Generated by
 * tools/port/port-dashboard.py -- regenerate rather than hand-editing.
 *
 * Titles, order, geometry and series are Big-hole's. Grafana applied derivative() to most
 * panels, so those metrics are wrapped in rate() here, except on gauges: Grafana
 * differenced whole streams, so `connections.current` was being plotted as a rate.
 *
 * Panels Grafana fanned out by regex or hardcoded index (per-disk, per-replica-member) use
 * a `*` glob, expanded against the capture catalogue at load time. A handful of queries
 * whose math did not match their title are corrected; each is justified in the porter.
 *
 * Grid is 24 columns to match Grafana 1:1.
 */

import type { Unit } from '../data/expr.js';

export interface PanelTemplate {
  readonly kind: 'chart' | 'section';
  readonly title: string;
  readonly metrics: readonly string[];
  readonly unit?: Unit;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export const DEFAULT_TEMPLATES: readonly PanelTemplate[] = [
  { kind: "section", title: "WiredTiger", metrics: [], x: 0, y: 0, w: 24, h: 1 },
  { kind: "chart", title: "WiredTiger Tickets", metrics: ["serverStatus.wiredTiger.concurrentTransactions.read.available", "serverStatus.wiredTiger.concurrentTransactions.write.available"], unit: "count", x: 0, y: 1, w: 14, h: 6 },
  { kind: "chart", title: "WiredTiger cache", metrics: ["serverStatus.wiredTiger.cache.maximum bytes configured", "serverStatus.wiredTiger.cache.bytes currently in the cache"], unit: "bytes", x: 14, y: 1, w: 10, h: 6 },
  { kind: "chart", title: "Mb read into cache / written from cache", metrics: ["rate(serverStatus.wiredTiger.cache.bytes written from cache)", "rate(serverStatus.wiredTiger.cache.bytes read into cache)"], unit: "bytes/s", x: 0, y: 7, w: 6, h: 6 },
  { kind: "chart", title: "Pages Evicted", metrics: ["rate(serverStatus.wiredTiger.cache.modified pages evicted)", "rate(serverStatus.wiredTiger.cache.unmodified pages evicted)"], x: 6, y: 7, w: 8, h: 6 },
  { kind: "chart", title: "Dirty mb in the cache", metrics: ["serverStatus.wiredTiger.cache.tracked dirty bytes in the cache"], unit: "bytes", x: 14, y: 7, w: 10, h: 7 },
  { kind: "chart", title: "Mb written for checkpoint", metrics: ["rate(serverStatus.wiredTiger.block-manager.bytes written for checkpoint)"], unit: "bytes/s", x: 0, y: 13, w: 6, h: 6 },
  { kind: "chart", title: "wiredTiger Block Manager", metrics: ["rate(serverStatus.wiredTiger.block-manager.bytes read)", "rate(serverStatus.wiredTiger.block-manager.bytes written)"], unit: "bytes/s", x: 6, y: 13, w: 8, h: 6 },
  { kind: "chart", title: "WiredTiger Data Handle", metrics: ["serverStatus.wiredTiger.data-handle.connection data handles currently active"], x: 14, y: 14, w: 10, h: 5 },
  { kind: "section", title: "Server Status", metrics: [], x: 0, y: 19, w: 24, h: 1 },
  { kind: "chart", title: "Memory", metrics: ["serverStatus.mem.virtual", "serverStatus.mem.resident"], unit: "bytes", x: 0, y: 20, w: 8, h: 5 },
  { kind: "chart", title: "Page faults", metrics: ["rate(serverStatus.extra_info.page_faults)"], x: 8, y: 20, w: 7, h: 5 },
  { kind: "chart", title: "Connections", metrics: ["serverStatus.connections.active", "serverStatus.connections.current", "rate(serverStatus.connections.totalCreated)"], x: 15, y: 20, w: 9, h: 7 },
  { kind: "chart", title: "Latency", metrics: ["div(rate(serverStatus.opLatencies.reads.latency), rate(serverStatus.opLatencies.reads.ops))", "div(rate(serverStatus.opLatencies.writes.latency), rate(serverStatus.opLatencies.writes.ops))", "div(rate(serverStatus.opLatencies.commands.latency), rate(serverStatus.opLatencies.commands.ops))"], unit: "us", x: 0, y: 25, w: 8, h: 7 },
  { kind: "chart", title: "Operations", metrics: ["rate(serverStatus.opcounters.update)", "rate(serverStatus.opcounters.query)", "rate(serverStatus.opcounters.insert)", "rate(serverStatus.opcounters.getmore)", "rate(serverStatus.opcounters.delete)", "rate(serverStatus.opcounters.command)"], x: 8, y: 25, w: 7, h: 7 },
  { kind: "chart", title: "Network requests", metrics: ["rate(serverStatus.network.numRequests)"], x: 15, y: 27, w: 9, h: 5 },
  { kind: "chart", title: "Current Queue writers / readers", metrics: ["serverStatus.globalLock.currentQueue.writers", "serverStatus.globalLock.currentQueue.readers"], x: 0, y: 32, w: 8, h: 6 },
  { kind: "chart", title: "Replica members health", metrics: ["replSetGetStatus.members.*.health"], unit: "count", x: 8, y: 32, w: 7, h: 6 },
  { kind: "chart", title: "Replica members lag", metrics: ["diff(serverStatus.localTime, replSetGetStatus.members.*.lastAppliedWallTime)"], unit: "ms", x: 15, y: 32, w: 9, h: 6 },
  { kind: "chart", title: "Operations latencies op", metrics: ["rate(serverStatus.opLatencies.reads.ops)", "rate(serverStatus.opLatencies.writes.ops)", "rate(serverStatus.opLatencies.commands.ops)"], unit: "per-sec", x: 0, y: 38, w: 8, h: 5 },
  { kind: "chart", title: "Server Uptime", metrics: ["serverStatus.uptime"], x: 8, y: 38, w: 7, h: 5 },
  { kind: "chart", title: "Replica members ping", metrics: ["replSetGetStatus.members.*.pingMs"], unit: "ms", x: 15, y: 38, w: 9, h: 5 },
  { kind: "chart", title: "FlowControl isLagged", metrics: ["scale(rate(serverStatus.flowControl.isLaggedTimeMicros), 0.0001)"], unit: "percent", x: 0, y: 43, w: 8, h: 6 },
  { kind: "chart", title: "Asserts", metrics: ["rate(serverStatus.asserts.warning)", "rate(serverStatus.asserts.user)", "rate(serverStatus.asserts.rollovers)", "rate(serverStatus.asserts.regular)", "rate(serverStatus.asserts.msg)"], x: 8, y: 43, w: 7, h: 7 },
  { kind: "chart", title: "Query Executor", metrics: ["rate(serverStatus.metrics.queryExecutor.scannedObjects)", "rate(serverStatus.metrics.queryExecutor.scanned)", "rate(serverStatus.metrics.queryExecutor.collectionScans.total)"], x: 15, y: 43, w: 9, h: 6 },
  { kind: "chart", title: "Commands", metrics: ["rate(serverStatus.metrics.commands.createIndexes.total)", "rate(serverStatus.metrics.commands.dataSize.total)", "rate(serverStatus.metrics.commands.dropIndexes.total)", "rate(serverStatus.metrics.commands.listCollections.total)", "rate(serverStatus.metrics.commands.listDatabases.total)"], x: 0, y: 49, w: 8, h: 6 },
  { kind: "chart", title: "avg Obj Size", metrics: ["local.oplog.rs.stats.avgObjSize"], x: 15, y: 49, w: 9, h: 6 },
  { kind: "chart", title: "Cursors", metrics: ["serverStatus.metrics.cursor.open.noTimeout", "serverStatus.metrics.cursor.open.pinned", "serverStatus.metrics.cursor.open.total", "serverStatus.metrics.cursor.timedOut"], x: 8, y: 50, w: 7, h: 6 },
  { kind: "chart", title: "Documents (deleted / inserted / returned / updated)", metrics: ["rate(serverStatus.metrics.document.updated)", "rate(serverStatus.metrics.document.returned)", "rate(serverStatus.metrics.document.inserted)", "rate(serverStatus.metrics.document.deleted)"], x: 0, y: 55, w: 8, h: 7 },
  { kind: "chart", title: "Opcounters Replica", metrics: ["rate(serverStatus.opcountersRepl.command)", "rate(serverStatus.opcountersRepl.delete)", "rate(serverStatus.opcountersRepl.getmore)", "rate(serverStatus.opcountersRepl.insert)", "rate(serverStatus.opcountersRepl.query)", "rate(serverStatus.opcountersRepl.update)"], x: 15, y: 55, w: 9, h: 7 },
  { kind: "chart", title: "Query Targeting: Scanned Objects / Returned ", metrics: ["div(rate(serverStatus.metrics.queryExecutor.scannedObjects), rate(serverStatus.metrics.document.returned))"], unit: "count", x: 8, y: 56, w: 7, h: 6 },
  { kind: "section", title: "System", metrics: [], x: 0, y: 62, w: 24, h: 1 },
  { kind: "chart", title: "Network In / Out physical", metrics: ["rate(serverStatus.network.physicalBytesIn)", "rate(serverStatus.network.physicalBytesOut)"], unit: "bytes/s", x: 0, y: 63, w: 8, h: 5 },
  { kind: "chart", title: "Network In / Out", metrics: ["rate(serverStatus.network.bytesOut)", "rate(serverStatus.network.bytesIn)"], x: 8, y: 63, w: 8, h: 6 },
  { kind: "chart", title: "Storage Size", metrics: ["local.oplog.rs.stats.freeStorageSize", "local.oplog.rs.stats.storageSize"], unit: "bytes", x: 16, y: 63, w: 8, h: 6 },
  { kind: "chart", title: "CPU Usage", metrics: ["pct(rate(systemMetrics.cpu.user_ms), sum(rate(systemMetrics.cpu.user_ms), rate(systemMetrics.cpu.system_ms), rate(systemMetrics.cpu.iowait_ms), rate(systemMetrics.cpu.nice_ms), rate(systemMetrics.cpu.softirq_ms), rate(systemMetrics.cpu.steal_ms), rate(systemMetrics.cpu.idle_ms)))", "pct(rate(systemMetrics.cpu.system_ms), sum(rate(systemMetrics.cpu.user_ms), rate(systemMetrics.cpu.system_ms), rate(systemMetrics.cpu.iowait_ms), rate(systemMetrics.cpu.nice_ms), rate(systemMetrics.cpu.softirq_ms), rate(systemMetrics.cpu.steal_ms), rate(systemMetrics.cpu.idle_ms)))", "pct(rate(systemMetrics.cpu.iowait_ms), sum(rate(systemMetrics.cpu.user_ms), rate(systemMetrics.cpu.system_ms), rate(systemMetrics.cpu.iowait_ms), rate(systemMetrics.cpu.nice_ms), rate(systemMetrics.cpu.softirq_ms), rate(systemMetrics.cpu.steal_ms), rate(systemMetrics.cpu.idle_ms)))"], unit: "percent", x: 0, y: 68, w: 8, h: 6 },
  { kind: "chart", title: "Disk writes and reads", metrics: ["rate(systemMetrics.disks.*.reads)", "rate(systemMetrics.disks.*.writes)"], unit: "per-sec", x: 8, y: 69, w: 8, h: 7 },
  { kind: "chart", title: "Memory", metrics: ["systemMetrics.memory.MemAvailable_kb", "systemMetrics.memory.MemFree_kb"], unit: "bytes", x: 16, y: 69, w: 8, h: 7 },
  { kind: "chart", title: "Disk I/O", metrics: ["scale(rate(systemMetrics.disks.*.io_time_ms), 0.1)", "scale(rate(systemMetrics.disks.*.io_queued_ms), 0.001)", "systemMetrics.disks.*.io_in_progress"], x: 0, y: 74, w: 8, h: 7 },
  { kind: "chart", title: "Disk writes", metrics: ["rate(systemMetrics.disks.*.write_sectors)", "div(rate(systemMetrics.disks.*.write_time_ms), rate(systemMetrics.disks.*.writes))", "rate(systemMetrics.disks.*.writes_merged)"], x: 8, y: 76, w: 8, h: 7 },
  { kind: "chart", title: "Swap Memory", metrics: ["systemMetrics.memory.SwapFree_kb", "systemMetrics.memory.SwapTotal_kb"], x: 16, y: 76, w: 8, h: 7 },
  { kind: "chart", title: "Disk reads", metrics: ["rate(systemMetrics.disks.*.read_sectors)", "div(rate(systemMetrics.disks.*.read_time_ms), rate(systemMetrics.disks.*.reads))", "rate(systemMetrics.disks.*.reads_merged)"], x: 0, y: 81, w: 8, h: 7 },
  { kind: "chart", title: "TCP ActiveOpens / AttemptFails / EstabResets", metrics: ["rate(systemMetrics.netstat.Tcp:ActiveOpens)", "rate(systemMetrics.netstat.Tcp:AttemptFails)", "rate(systemMetrics.netstat.Tcp:EstabResets)"], x: 8, y: 83, w: 8, h: 7 },
  { kind: "chart", title: "TCP: InSegs / OutSegs", metrics: ["rate(systemMetrics.netstat.Tcp:InSegs)", "rate(systemMetrics.netstat.Tcp:OutSegs)"], x: 16, y: 83, w: 8, h: 5 },
  { kind: "chart", title: "TCP Routing Issues", metrics: ["rate(systemMetrics.netstat.Ip:OutNoRoutes)"], x: 0, y: 88, w: 8, h: 5 },
  { kind: "chart", title: "TCP Connection Issues", metrics: ["systemMetrics.netstat.Tcp:CurrEstab", "rate(systemMetrics.netstat.Tcp:EstabResets)", "rate(systemMetrics.netstat.Tcp:OutRsts)"], x: 8, y: 90, w: 8, h: 7 },
  { kind: "chart", title: "TCP Packet Loss or Corruption", metrics: ["rate(systemMetrics.netstat.Tcp:InCsumErrors)", "rate(systemMetrics.netstat.Tcp:InErrs)", "rate(systemMetrics.netstat.Tcp:RetransSegs)", "rate(systemMetrics.netstat.Ip:InDiscards)", "rate(systemMetrics.netstat.Ip:OutDiscards)"], x: 0, y: 93, w: 8, h: 5 },
];
