"""Port the devops-land/mongodb_ftdc_viewer Grafana dashboard to ftdc-lens panel specs.

Grafana applies derivative() to most panels; those become rate() here. Panels whose Flux
does something we cannot express generically (per-disk regex fans, CPU percent, replica lag)
are hand-mapped below and expanded against the capture catalogue at load time via `*` globs.
"""
import json, re, sys

src = sys.argv[1]
d = json.load(open(src))

UNITS = {
    'decgbytes': 'bytes', 'decbytes': 'bytes', 'bytes': 'bytes',
    'deckbytes': 'bytes',            # values are kB; scaled to bytes in the expression
    'MBs': 'bytes/s', 'ms': 'ms', 'µs': 'us', 'ns': 'us',
    'percent': 'percent', 'short': 'count', 'none': 'count',
}

# Panels whose queries are not a plain field list. Values are expression templates; `*`
# expands against the catalogue so every disk / mount / replica member is picked up.
HAND = {
    'Replica members lag': (
        [f'diff(serverStatus.localTime, replSetGetStatus.members.*.lastAppliedWallTime)'], 'ms'),
    'Replica members ping': (['replSetGetStatus.members.*.pingMs'], 'ms'),
    # Upstream hardcoded members 0/1/2; glob so any set size works.
    'Replica members health': (['replSetGetStatus.members.*.health'], 'count'),
    'Replica members state': (['replSetGetStatus.members.*.state'], 'count'),
    'CPU Usage': ([f'scale(rate(systemMetrics.cpu.{k}_ms), 0.1)'
                   for k in ('user', 'system', 'iowait', 'nice', 'softirq', 'steal', 'idle')], 'percent'),
    'Disk I/O': (['rate(systemMetrics.disks.*.io_time_ms)',
                  'systemMetrics.disks.*.io_in_progress'], 'count'),
    'Disk writes and reads': (['rate(systemMetrics.disks.*.reads)',
                               'rate(systemMetrics.disks.*.writes)'], 'per-sec'),
    'Disk writes': (['rate(systemMetrics.disks.*.write_sectors)',
                     'rate(systemMetrics.disks.*.write_time_ms)'], 'count'),
    'Disk reads': (['rate(systemMetrics.disks.*.read_sectors)',
                    'rate(systemMetrics.disks.*.read_time_ms)'], 'count'),
}
# kB-valued fields are scaled to real bytes so the unit formatter is honest.
KB_FIELDS = re.compile(r'_kb$')

panels = []
for p in d.get('panels', []):
    gp = p.get('gridPos', {})
    title = p.get('title', '')
    if p.get('type') == 'row':
        panels.append({'kind': 'section', 'title': title,
                       'x': gp.get('x', 0), 'y': gp.get('y', 0), 'w': gp.get('w', 24), 'h': 1,
                       'metrics': []})
        continue

    unit = UNITS.get(p.get('fieldConfig', {}).get('defaults', {}).get('unit', ''), 'count')

    if title in HAND:
        metrics, unit = HAND[title]
    else:
        queries = ' '.join((t.get('query') or '') for t in p.get('targets', []))
        derive = 'derivative(' in queries
        fields, seen = [], set()
        for t in p.get('targets', []):
            for f in re.findall(r'r\["?_field"?\]\s*==\s*"([^"]+)"', t.get('query') or ''):
                if f not in seen:
                    seen.add(f); fields.append(f)
        if not fields:
            continue
        metrics = []
        for f in fields:
            e = f'scale({f}, 1024)' if KB_FIELDS.search(f) else f
            metrics.append(f'rate({e})' if derive else e)
        if derive and unit == 'bytes':
            unit = 'bytes/s'
        elif derive and unit == 'count':
            unit = 'per-sec'

    panels.append({'kind': 'chart', 'title': title, 'metrics': metrics, 'unit': unit,
                   'x': gp.get('x', 0), 'y': gp.get('y', 0),
                   'w': gp.get('w', 8), 'h': gp.get('h', 6)})

out = [
    '/**',
    ' * Default dashboard.',
    ' *',
    ' * Ported from the Grafana dashboard in devops-land/mongodb_ftdc_viewer (MIT), which is',
    ' * itself a descendant of zelmario/Big-hole. Generated by tools/port/port-dashboard.py --',
    ' * regenerate rather than hand-editing if the upstream dashboard changes.',
    ' *',
    ' * Grafana applied derivative() to most panels, so those metrics are wrapped in rate()',
    ' * here. Panels whose Flux fanned out over a regex (per-disk, per-replica-member) use a `*`',
    ' * glob, expanded against the capture catalogue at load time.',
    ' *',
    ' * Grid is 24 columns to match Grafana 1:1.',
    ' */',
    '',
    "import type { Unit } from '../data/expr.js';",
    '',
    'export interface PanelTemplate {',
    "  readonly kind: 'chart' | 'section';",
    '  readonly title: string;',
    '  readonly metrics: readonly string[];',
    '  readonly unit?: Unit;',
    '  readonly x: number;',
    '  readonly y: number;',
    '  readonly w: number;',
    '  readonly h: number;',
    '}',
    '',
    'export const DEFAULT_TEMPLATES: readonly PanelTemplate[] = [',
]
for p in panels:
    metrics = ', '.join(json.dumps(m) for m in p['metrics'])
    unit = f", unit: {json.dumps(p['unit'])}" if p['kind'] == 'chart' else ''
    out.append(f"  {{ kind: {json.dumps(p['kind'])}, title: {json.dumps(p['title'])}, "
               f"metrics: [{metrics}]{unit}, "
               f"x: {p['x']}, y: {p['y']}, w: {p['w']}, h: {p['h']} }},")
out.append('];')
out.append('')
print('\n'.join(out))
